
use std::collections::HashMap;

use anyhow::Result;

use rude_util::{apply_alias, extract_crate_name, format_lines_opt, relative_path};

use super::query::load_or_build_graph;

pub fn run_dead(
    include_pub: bool,
    file_filter: Option<String>,
) -> Result<()> {

    let graph = load_or_build_graph()?;
    let n = graph.chunks.len();
    let (alias_map, _) = graph.global_aliases();

    // Count chunks sharing the same (file, start_line) — used to detect macro expansions
    // where a single #[attribute] produces many synthetic functions at one source location.
    let mut colocated: HashMap<(String, usize), usize> = HashMap::new();
    for c in &graph.chunks {
        if let Some((s, _)) = c.lines {
            *colocated.entry((c.file.clone(), s)).or_default() += 1;
        }
    }

    let mut file_line_cache: HashMap<String, Option<usize>> = HashMap::new();
    let mut dead: Vec<usize> = Vec::new();
    let mut stale_skipped: usize = 0;

    for i in 0..n {
        if graph.is_test[i] || graph.chunks[i].kind != "function" {
            continue;
        }
        if is_derive_generated(&graph.chunks[i].name) {
            continue;
        }
        if is_macro_generated(&graph.chunks[i], &colocated) {
            continue;
        }
        if let Some(ref filter) = file_filter {
            if !graph.chunks[i].file.contains(filter.as_str()) {
                continue;
            }
        }
        if !graph.callers[i].is_empty() {
            continue;
        }
        if !include_pub {
            let is_pub = graph.chunks[i].signature
                .as_deref()
                .is_some_and(|s| s.starts_with("pub ") || s.starts_with("pub(crate)"));
            if is_pub {
                continue;
            }
        }
        if graph.chunks[i].name.starts_with('<') && graph.chunks[i].name.contains(" as ") {
            continue;
        }
        let name = &graph.chunks[i].name;
        if name == "main" || name.ends_with("::main") {
            continue;
        }
        let file = &graph.chunks[i].file;
        if !rude_util::is_supported_code_file(file) {
            continue;
        }
        if name.contains("::check::assert_impl")
            || name.contains("::{closure#0}::check")
            || name.ends_with("::new") && graph.callees[i].is_empty()
        {
            continue;
        }

        // Stale DB detection: file missing on disk, or chunk line range exceeds file length.
        if is_stale(&graph.chunks[i], &mut file_line_cache) {
            stale_skipped += 1;
            continue;
        }

        dead.push(i);
    }

    let mut by_crate: std::collections::BTreeMap<String, Vec<usize>> = std::collections::BTreeMap::new();
    for &i in &dead {
        let c = &graph.chunks[i];
        let crate_name = if c.crate_name.is_empty() { extract_crate_name(&c.file) } else { c.crate_name.clone() };
        by_crate.entry(crate_name).or_default().push(i);
    }

    println!("=== dead code: {} functions with no callers ===\n", dead.len());

    for (crate_name, indices) in &by_crate {
        println!("[{}] {} dead:", crate_name, indices.len());
        for &i in indices {
            let loc = format_lines_opt(graph.chunks[i].lines);
            let rel = relative_path(&graph.chunks[i].file);
            let short = apply_alias(rel, &alias_map);
            println!("  {short}{loc}  {}", graph.chunks[i].dn());
        }
        println!();
    }

    if stale_skipped > 0 {
        println!("stale: {stale_skipped} (run `rude add .` to refresh)");
    }

    Ok(())
}

fn is_derive_generated(name: &str) -> bool {
    name.contains("::_serde::") || name.contains("::_::_serde::")
    || name.contains("as bincode::Encode>::encode")
    || name.contains("as bincode::Decode<")
    || name.contains("as bincode::BorrowDecode<")
    || name.contains("as clap::")
}

// Heuristic: detect functions generated by proc macros (e.g., dioxus #[component]).
// These manifest as synthetic builder methods sharing a file+line with siblings and
// usually lack a user-authored signature.
fn is_macro_generated(
    chunk: &rude_intel::parse::ParsedChunk,
    colocated: &HashMap<(String, usize), usize>,
) -> bool {
    let name = chunk.name.as_str();
    if name.contains("::into_value")
        || name.ends_with("::build")
        || name.contains("::__build")
        || name.contains("::Builder")
        || name.contains("Builder::")
        || name.contains("props::")
        || name.contains("::Props::")
    {
        return true;
    }
    // Multiple chunks at the same (file, start_line) strongly suggest macro expansion.
    let sig_empty = chunk.signature.as_deref().map(str::is_empty).unwrap_or(true);
    if sig_empty {
        if let Some((s, _)) = chunk.lines {
            if colocated.get(&(chunk.file.clone(), s)).copied().unwrap_or(0) >= 2 {
                return true;
            }
        }
    }
    false
}

fn is_stale(
    chunk: &rude_intel::parse::ParsedChunk,
    cache: &mut HashMap<String, Option<usize>>,
) -> bool {
    let path = std::path::Path::new(&chunk.file);
    if !path.exists() {
        return true;
    }
    let Some((_, end)) = chunk.lines else { return false };
    let total = cache.entry(chunk.file.clone()).or_insert_with(|| {
        std::fs::read_to_string(path).ok().map(|s| s.lines().count())
    });
    matches!(*total, Some(t) if end > t)
}
